version: '3.8'

services:
  web:
    build: ./backend
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web  
  db:
    image: mariadb:11
    container_name: mysql-db
    restart: always
    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"  
    volumes:
      - database_data:/var/lib/mysql
  redis:
    image: redis:7.2
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  database_data:
  redis_data: 
